name: Project Radiance Beatmap Devtool

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3 python3-pip
        pip3 install pyinstaller

    - name: Build Windows executable
      run: |
        pyinstaller --onefile --distpath ./dist/windows/ --name ProjectRadianceBeatmapDevtool Main.py

    - name: Build Mac executable
      run: |
        pip3 install py2app
        py2applet --make-setup Main.py
        python3 setup.py py2app -A

    - name: Build Linux executable
      run: |
        sudo apt-get install build-essential
        pip3 install cx-Freeze
        cxfreeze Main.py --target-dir=./dist/linux/

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: executables
        path: |
          dist/windows/
          dist/mac/
          dist/linux/
