name: Project Radiance Beatmap Devtool

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  RELEASE_VERSION: 0.1.0

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-pip
          pip3 install pyinstaller

      - name: Build Linux executable
        run: |
          sudo apt-get install build-essential
          pip3 install cx-Freeze
          cxfreeze Main.py --target-dir=./dist/linux/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bundle-osx
          path: project-radiance-beatmap-devtool-linux-${{env.RELEASE_VERSION}}.zip

  build-mac:
    runs-on: macos-12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-pip
          pip3 install pyinstaller

      - name: Build Mac executable
        run: |
          pip3 install py2app
          py2applet --make-setup Main.py
          python3 setup.py py2app -A

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bundle-osx
          path: project-radiance-beatmap-devtool-mac-${{env.RELEASE_VERSION}}.zip

  build-windows:
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3 python3-pip
        pip3 install pyinstaller

    - name: Build Windows executable
      run: |
        pyinstaller --onefile --distpath ./dist/windows/ --name ProjectRadianceBeatmapDevtool Main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: bundle-osx
        path: project-radiance-beatmap-devtool-windows-${{env.RELEASE_VERSION}}.zip

  publish:
    runs-on: ubuntu-latest

    needs:
      - build-linux
      - build-mac
      - build-windows

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: List files
        run: ls -R

      - name: Publish artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: bundle-linux/project-radiance-beatmap-devtool-linux-${{env.RELEASE_VERSION}}.tar, bundle-osx/project-radiance-beatmap-devtool-osx-${{env.RELEASE_VERSION}}.zip, bundle-windows/project-radiance-beatmap-devtool-win-${{env.RELEASE_VERSION}}.zip
          tag: '${{env.RELEASE_VERSION}}'
