name: Project Radiance Beatmap Devtool

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  RELEASE_VERSION: 0.1.0

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4.1.0
        with:
          python-version: "3.9.x"

      - name: upgrade python pip
        run: |
          python3 -m pip install --upgrade pip
          pip install pyinstaller

      - name: build binary
        run: |
          python -m PyInstaller Main.py --onefile --distpath ./project-radiance

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bundle-linux
          path: project-radiance-beatmap-devtool-linux-${{env.RELEASE_VERSION}}.zip

  build-mac:
    runs-on: macos-12

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4.1.0
        with:
          python-version: "3.9.x"

      - name: upgrade python pip
        run: |
          python3 -m pip install --upgrade pip
          pip install pyinstaller

      - name: build binary
        run: |
          python -m PyInstaller Main.py --onefile --distpath ./project-radiance

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bundle-mac
          path: project-radiance-beatmap-devtool-mac-${{env.RELEASE_VERSION}}.zip

  build-windows:
    runs-on: windows-2019

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4.1.0
        with:
          python-version: "3.9.x"

      - name: upgrade python pip
        run: |
          python3 -m pip install --upgrade pip
          pip install pyinstaller

      - name: build binary
        run: |
          python -m PyInstaller Main.py --onefile --distpath ./project-radiance

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bundle-windows
          path: project-radiance-beatmap-devtool-windows-${{env.RELEASE_VERSION}}.zip

  publish:
    runs-on: ubuntu-latest

    needs:
      - build-linux
      - build-mac
      - build-windows

    steps:
      - name: download artifacts
        uses: actions/download-artifact@v3

      - name: list files
        run: ls -R

      - name: publish artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: bundle-linux/project-radiance-beatmap-devtool-linux-${{env.RELEASE_VERSION}}.zip, bundle-mac/project-radiance-beatmap-devtool-mac-${{env.RELEASE_VERSION}}.zip, bundle-windows/project-radiance-beatmap-devtool-windows-${{env.RELEASE_VERSION}}.zip
          tag: '${{env.RELEASE_VERSION}}'
