name: Project Radiance Beatmap Devtool

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  RELEASE_VERSION: 0.1.0

jobs:
#  build-linux:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: checkout repository
#        uses: actions/checkout@v2
#
#      - name: setup python
#        uses: actions/setup-python@v4.1.0
#        with:
#          python-version: "3.9.x"
#
#      - name: upgrade python pip
#        run: |
#          python3 -m pip install --upgrade pip
#          pip install pyinstaller
#
#      - name: build binary
#        run: |
#          python -m PyInstaller ProjectRadianceBeatmapDevtool.py --onefile --distpath ./project-radiance
#
#      - name: upload artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: bundle-linux
#          path: ProjectRadianceBeatmapDevtool.exe

#  build-mac:
#    runs-on: macos-12
#
#    steps:
#      - name: checkout repository
#        uses: actions/checkout@v2
#
#      - name: setup python
#        uses: actions/setup-python@v4.1.0
#        with:
#          python-version: "3.9.x"
#
#      - name: upgrade python pip
#        run: |
#          python3 -m pip install --upgrade pip
#          pip install pyinstaller
#
#      - name: build binary
#        run: |
#          python -m PyInstaller ProjectRadianceBeatmapDevtool.py --onefile --distpath ./project-radiance
#
#      - name: upload artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: bundle-mac
#          path: ProjectRadianceBeatmapDevtool.exe

  build-windows:
    runs-on: windows-2019

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4.1.0
        with:
          python-version: "3.9.0"

      - name: upgrade python pip
        run: |
          python3 -m pip install --upgrade pip
          pip install pyinstaller

      - name: build binary
        run: |
          python -m PyInstaller ProjectRadianceBeatmapDevtool.spec

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bundle-windows
          path: dist/ProjectRadianceBeatmapDevtool.exe

  publish:
    runs-on: ubuntu-latest

    needs:
#      - build-linux
#      - build-mac
      - build-windows

    steps:
      - name: download artifacts
        uses: actions/download-artifact@v3

      - name: list files
        run: ls -R

      - name: upload windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: ProjectRadianceBeatmapDevtool.exe
          path: |
            dist/
            dist

# bundle-linux/ProjectRadianceBeatmapDevtool.exe, bundle-mac/ProjectRadianceBeatmapDevtool.exe,